#!/bin/bash

ROOT=$(readlink -f $(dirname ${0}))

mkdir -p .build
pushd .build

git clone --depth 5 https://github.com/vim/vim vim

git clone --depth 1 --single-branch -b 3.9 https://github.com/python/cpython python3
cp python3/PC/pyconfig.h python3/Include

git clone --depth 1 --single-branch -b v2.1 https://github.com/LuaJIT/LuaJIT LuaJIT

pushd vim

git apply ${ROOT}/patches/modern_icon.patch
git apply ${ROOT}/patches/tabline-close.patch
git apply ${ROOT}/patches/feat_proportional_fonts.patch
git apply ${ROOT}/patches/gui_cmd.patch

make -C src -f Make_ming.mak \
    CC="" CXX="" \
    CROSS_COMPILE=x86_64-w64-mingw32- WINDRES=x86_64-w64-mingw32-windres \
    GUI=yes \
    VIMDLL=yes \
    PROPORTIONAL_FONTS=yes \
    LUA=../../LuaJIT/src DYNAMIC_LUA=yes LUA_VER=51 \
    PYTHON3=yes PYTHON3INC=-I../../python3/Include PYTHON3_VER=39 \
    STATIC_STDCPLUS=yes \
    -j 6

popd

popd

mkdir -p release
cp -r .build/vim/src/vim64.dll .build/vim/src/vim.exe .build/vim/src/gvim.exe .build/vim/runtime .build/vim/src/vimrun.exe release
