name: nocd5 Nightly Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron:  "30 22 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup
      run: sudo apt install build-essential mingw-w64

    - name: Build
      run: bash ./build

    - name: Set Vars
      id: set_vars
      run: |
        pushd .build/vim
        echo "::set-output name=tag::$(git describe --tags --abbrev=0)"
        popd

    - name: Create Archive
      run: |
        pushd release
        7z a ../vim_${{ steps.set_vars.outputs.tag }}.zip *
        popd

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.set_vars.outputs.tag }}
        release_name: ${{ steps.set_vars.outputs.tag }}
        draft: false
        prerelease: false

    - name: Upload
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: vim_${{ steps.set_vars.outputs.tag }}.zip
        asset_name: vim_${{ steps.set_vars.outputs.tag }}.zip
        asset_content_type: application/zip
