name: nocd5 Nightly Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron:  "30 22 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Setup
      run: sudo apt install build-essential mingw-w64

    - name: Build
      run: bash ./build

    - name: Set Vars
      id: set_vars
      run: |
        pushd .build/vim
        echo "vim_tag=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
        popd

    - name: Create Archive
      run: |
        pushd release
        7z a ../vim_${{ env.vim_tag }}.zip *
        popd

    - name: Create Release
      id: create_release
      run: gh release create ${{ env.vim_tag }} --generate-notes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload
      run: gh release upload ${{ env.vim_tag }} vim_${{ env.vim_tag }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
