name: nocd5 Nightly Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron:  "30 22 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Setup
      run: sudo apt install build-essential mingw-w64

    - name: Build
      run: bash ./build

    - name: Set Vars
      id: set_vars
      run: |
        pushd .build/vim
        echo "::set-output name=tag::$(git describe --tags --abbrev=0)"
        popd

    - name: Create Archive
      run: |
        pushd release
        7z a ../vim_${{ steps.set_vars.outputs.tag }}.zip *
        popd

    - name: Create Release
      id: create_release
      run: gh release create ${{ steps.set_vars.outputs.tag }} --generate-notes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload
      run: gh release upload ${{ steps.set_vars.outputs.tag }} vim_${{ steps.set_vars.outputs.tag }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
